/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChargeOffAccount struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Do not use the PRN if more than one card has ever been associated with this account. Pattern: PAN or PRN Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// A JSON object containing a list of charge-off details. See the endpoint description above for details. Pattern: JSON format (list of dictionaries) Example: `\"[{\"chargeOffAmount\": 2.6, \"chargeOffReason\": 5}, {\"chargeOffAmount\": 4.75, \"chargeOffReason\": 2}]\"`
	ChargeOffDetails string `json:"chargeOffDetails,omitempty"`
	// If `accountNo` is a secondary account, pass `1` to close all accounts with the same balance ID. Pattern: `0` or `1` Example: `1`
	CloseAssociatedAccounts int32 `json:"closeAssociatedAccounts,omitempty"`
}
