/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData18 struct {
	// A token that is used to authenticate a HTTP post for sensitive data, such as PAN or a PIN
	Token string `json:"token"`
	// The date and time a token expires
	Expires time.Time `json:"expires"`
}
