/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PendingDeposit struct {
	// A fee or transaction charge
	Amt float32 `json:"amt"`
	// An initial timestamp for the creation of the record
	InTs time.Time `json:"in_ts"`
	// A timestamp for an ACH record that specifies when the payment posts
	EffectiveDt time.Time `json:"effective_dt"`
	// The name of the account receiving the flagged deposit
	Name string `json:"name"`
	// An account ID that can be used instead of the PAN or other restricted information
	Xid string `json:"xid"`
	// An ID number unique to a program
	ProgId string `json:"prog_id"`
	// A record of a batch of transactions
	BatchHdr string `json:"batch_hdr,omitempty"`
	// The destination account for a flagged pending deposit
	DestAcctNo string `json:"dest_acct_no"`
	// An ID (Usually a bank routing number) for the institution that originated the deposit
	SourceInstId string `json:"source_inst_id,omitempty"`
	// The name of the institution that originated the deposit
	SourceInstName string `json:"source_inst_name,omitempty"`
	// The status of the deposit. See <a href=\"ref:api-reference-deposit-status-codes\" target=\"_blank\">Deposit Status Codes</a>.
	Status string `json:"status,omitempty"`
	// Transaction type
	TransType string `json:"trans_type,omitempty"`
	// Supplemental information to identify a deposit
	AddendaRec string `json:"addenda_rec,omitempty"`
	// List containing information about categories
	Categories []PendingDepositCategories `json:"categories,omitempty"`
	// A unique ID for an ACH transaction
	AchTransId string `json:"ach_trans_id"`
}
