/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A data structure that lists one or more carriers
type ResponseData48Carriers struct {
	// An ID number assigned to the associated carrier
	CarrierId string `json:"carrier_id"`
	// A domain name to be used for translating emails to text messages with various phone carriers
	EmailGateway string `json:"email_gateway"`
	// The name of the mobile phone service carrier
	CarrierName string `json:"carrier_name"`
	// The name of the mobile phone service carrier
	CarrierDisplayName string `json:"carrier_display_name"`
}
