/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData25Deposits struct {
	// A fee or transaction charge
	Amt string `json:"amt"`
	// Timestamp for the initial creation of the record
	InTs time.Time `json:"in_ts"`
	// Date when the ACH payment posts
	EffectiveDt time.Time `json:"effective_dt"`
	// The name of the account receiving the deposit
	Name string `json:"name"`
	// Encrypted cardholder first name
	Efname string `json:"efname,omitempty"`
	// Encrypted cardholder last name
	Elname string `json:"elname,omitempty"`
	// An account ID that can be used instead of the PAN
	Xid string `json:"xid,omitempty"`
	// Identifier for the program associated with the account
	ProgId string `json:"prog_id"`
	// A record of a batch of transactions
	BatchHdr string `json:"batch_hdr,omitempty"`
	// The destination account for a pending deposit
	DestAcctNo string `json:"dest_acct_no,omitempty"`
	// An ID (usually a bank routing number) for the institution that originated the deposit
	SourceInstId string `json:"source_inst_id"`
	// The name of the institution that originated the deposit
	SourceInstName string `json:"source_inst_name"`
	// An account number of the institution that originated the deposit
	SourceAcctNo string `json:"source_acct_no,omitempty"`
	// The status of the deposit. See <a href=\"ref:api-reference-deposit-status-codes\" target=\"_blank\">Deposit Status Codes</a>.
	Status string `json:"status"`
	// Transaction type
	TransType string `json:"trans_type"`
	// Supplemental information to identify a deposit
	AddendaRec string `json:"addenda_rec,omitempty"`
	// A unique ID for an ACH transaction
	AchTransId string `json:"ach_trans_id"`
	// Galileo-generated account number. Also called the PRN.
	PmtRefNo string `json:"pmt_ref_no,omitempty"`
	Categories []DepositCategories `json:"categories,omitempty"`
}
