/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModifyOnDemandAlertStatus struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// Galileo-generated identifier for a product. Pattern: Integer Example: `501`
	ProdId int32 `json:"prodId"`
	// Account holder's mobile phone number. Pattern: Exactly 10 digits, no hyphens or other characters Example: `\"8013656050\"`
	MobilePhone string `json:"mobilePhone"`
	// Account holder's mobile carrier. Configurable list. Pattern: Configurable list Example: `8`
	MobileCarrierId int32 `json:"mobileCarrierId"`
	// Type of action to perform. See the <a href=\"ref:api-reference-on-demand-alert-statuses\" target=\"_blank\">On-Demand Alert Statuses</a> enumeration for valid values. Pattern: One character Example: `\"E\"`
	ActionType string `json:"actionType"`
	// When `actionType: C`, this value will be validated against what was sent to the cardholder via text message. Pattern: 4-digit string Example: `\"1234\"`
	VerificationPin string `json:"verificationPin,omitempty"`
}
