/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData111 struct {
	// The top up end date
	TopUpEndDate time.Time `json:"top_up_end_date"`
	// The top up end date
	Amount string `json:"amount"`
}
