/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData120 struct {
	// The balance on the account after the reversal is processed
	NewBalance float64 `json:"new_balance"`
	// The balance on the account before the reversal is processed
	OldBalance float64 `json:"old_balance"`
	// Galileo generated adjustment transaction ID
	AdjustmentTransId int32 `json:"adjustment_trans_id"`
	// A number that represents transaction
	TransactionId string `json:"transaction_id"`
}
