/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type BalanceData struct {
	// Balance as of date
	BalanceDate time.Time `json:"balance_date"`
	// The bank name
	BankName string `json:"bank_name"`
	// Account balance
	BalanceAmount float32 `json:"balance_amount"`
	// Rate tier balance
	RateTierBalance float32 `json:"rate_tier_balance"`
	// The accrued interest amount
	AccruedInterest float32 `json:"accrued_interest"`
	// Bank number
	BankNumber int32 `json:"bank_number"`
	// Rate record number
	RateRecordNumber int32 `json:"rate_record_number"`
}
