/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetTopUp struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// Numeric bank account number. Pattern: Numeric string of up to 22 characters in length. Example: `\"4483434234348\"`
	AccountNo string `json:"accountNo"`
	// Currency amounts passed as whole or fractional amounts, examples: '100.00', '100', or '100.73'.  Pattern: Monetary amount 0 or greater. Example: `25.50`
	Amount float32 `json:"amount"`
	// Specifies the last date that a daily top up should be performed. Pattern: `YYYY-MM-DD` Example: `\"2016-01-01\"`
	TopUpEndDate string `json:"topUpEndDate"`
}
