/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SetAccountFeature struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>>, <<glossary:PAN>> or <<glossary:CAD>> of the account. Pattern: PAN, PRN, or CAD Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// Consult the **featureType** column in the <a href=\"ref:api-reference-set-account-feature-values\" target=\"_blank\">Set Account Feature Values</a> table for valid values. Pattern: Integer Example: `3`
	FeatureType int32 `json:"featureType"`
	// Consult the **featureValue** column in the <a href=\"ref:api-reference-set-account-feature-values\" target=\"_blank\">Set Account Feature Values</a> table for valid values. Pattern: As specified in the **featureValue** column Example: `Y`
	FeatureValue string `json:"featureValue,omitempty"`
	// The starting date-time for the date range. Default: current date-time Pattern: YYYY-MM-DD hh:mm:ss Example: `\"2016-01-01 10:10:15\"`
	StartDate time.Time `json:"startDate,omitempty"`
	// The ending date-time for the date range; must be equal to or later than `startDate`. Default: 3000-01-01 00:01:00 Pattern: YYYY-MM-DD hh:mm:ss Example: `\"2016-02-01 10:10:10\"`
	EndDate time.Time `json:"endDate,omitempty"`
}
