/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A dictionary of values that are returned by Plaid. The RPVIR parameter must be set to `1` to receive this object.
type ResponseData104PlaidIdentityValues struct {
	Emails []string `json:"emails,omitempty"`
	Names []string `json:"names,omitempty"`
	Phones []string `json:"phones,omitempty"`
	ZipCodes []string `json:"zip_codes,omitempty"`
}
