/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetAccountLevelAuthControlBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// The <<glossary:PRN>> for the account. Do not use the <<glossary:CAD>> or <<glossary:PAN>>. Pattern: 12-digit numeric string Example: `\"344101254935\"`
	AccountNo string `json:"accountNo"`
	// The control ID of the velocity control to set or modify, as returned by <a href=\"ref:post_getauthcontrol\" target=\"_blank\">Get Auth Control</a>. Pattern: Integer, max  18 digits Example: 10492
	ControlId int32 `json:"controlId"`
	// The amount of the new limit. If this parameter is not populated when creating a new control, then `transactionCount` is required Pattern: Decimal number (14, 2) Example: `500.00`
	Amount float32 `json:"amount,omitempty"`
	// New number of transactions to permit. If this parameter is not populated when creating a new control, then `amount` is required. Pattern: Integer, maximum 18 digits Example: `5`
	TransactionCount int32 `json:"transactionCount,omitempty"`
	// Start date-time for the control. Can be set up to six months in the future. Cannot be in the past. Must be earlier than `endDate`. Default: Current <a href=\"ref:galileo-system-time\" target=\"_blank\">Galileo system time</a>  Pattern: YYYY-MM-DD hh:mm:ss or YYYY-MM-DD Example: `\"2022-03-03 00:00:00\"`
	StartDate string `json:"startDate,omitempty"`
	// End date-time for the control. Must be later than `startDate`. Cannot be in the past. Default: `3000-01-01 00:00:00`.  Pattern: YYYY-MM-DD hh:mm:ss or YYYY-MM-DD Example: `\"2022-03-10 23:59:59\"`
	EndDate string `json:"endDate,omitempty"`
}
