/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModifyLocationFeeResponseData struct {
	// Active flag for the fee.
	Active string `json:"active"`
	// The maximum amount to charge, when `amount_type` is `percent`.
	MaxFee string `json:"max_fee"`
	// Galileo ID of the location, when `locationType` is `0` or `2`.
	Location int32 `json:"location"`
	// Customer ID of the location, when `locationType` is `1`.
	ProviderSpecifiedId string `json:"provider_specified_id"`
	// The minimum amount to charge, when `amount_type` is `percent`.
	MinFee string `json:"min_fee"`
	// Type of fee, `FBD` (FBE direct deposit fee) or `DEL` (ACH direct deposit fee).
	FeeType string `json:"fee_type"`
	// Amount of the fee.
	Amount string `json:"amount"`
	// The type of the amount: `flat` or `percent`.
	AmountType string `json:"amount_type"`
}
