/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetLocationFee struct {
	// Y/N field, determines if the fee is active
	Active string `json:"active,omitempty"`
	// Amount of fee
	Amount float32 `json:"amount,omitempty"`
	// Type of amount: flat or percent
	AmountType string `json:"amount_type,omitempty"`
	// Maximum amount of fee
	MaxFee float32 `json:"max_fee,omitempty"`
	// Type of fee, current support FBD and DEL
	FeeType string `json:"fee_type,omitempty"`
	// Minimum amount of the fee
	MinFee float32 `json:"min_fee,omitempty"`
}
