/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductMccRestrictions struct {
	// Starting MCC for the range
	RangeStart int32 `json:"range_start"`
	// Ending MCC for the range
	RangeEnd int32 `json:"range_end"`
	// Indicates if the MCC should be restricted for online transactions only
	OnlineOnly string `json:"online_only"`
}
