/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PendingMerchantCredit struct {
	// ID that has been assigned a transaction that has been settled
	SettleId string `json:"settle_id"`
	// Timestamp for settled transaction
	SettleTs time.Time `json:"settle_ts"`
	// The amount of pending merchant credit
	Amount float64 `json:"amount"`
	// The description of a pending merchant credit
	Description string `json:"description"`
	// A Galileo generated account number
	PmtRefNo string `json:"pmt_ref_no"`
	// ID of the card as found in the RDF
	CardId string `json:"card_id"`
	// A person's first name as listed on the account
	FirstName string `json:"first_name"`
	// A person's last name as listed on the account
	LastName string `json:"last_name"`
}
