/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Card2EmbossedCards struct {
	// UUID for an emboss record that has been sent to the embosser. When this field is present outside the `embossed_cards` object, it contains the most recent emboss UUID.
	EmbossUuid string `json:"emboss_uuid,omitempty"`
	// Date the card was created
	CreatedDate string `json:"created_date"`
	// Date the card was embossed
	EmbossDate string `json:"emboss_date"`
	// Expiration date of the card
	ExpiryDate time.Time `json:"expiry_date,omitempty"`
	// The status of the card
	Status string `json:"status"`
	// The type of shipping used for the card
	ShippingType string `json:"shipping_type"`
}
