/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData5Customer struct {
	// The first name on a profile
	FirstName string `json:"first_name"`
	// The middle name on a profile
	MiddleName string `json:"middle_name"`
	// The last name on a profile
	LastName string `json:"last_name"`
	// Street and residence number on the account
	Address1 string `json:"address_1"`
	// Additional address information on the account
	Address2 string `json:"address_2"`
	// City for address information
	City string `json:"city"`
	// State for address information
	State string `json:"state"`
	// A postal code for the address information
	PostalCode string `json:"postal_code"`
	// The ISO 3166 international standard for country codes
	CountryCode string `json:"country_code"`
	// The home phone number on a profile
	Phone string `json:"phone"`
	// The home phone number on a profile
	MobilePhone string `json:"mobile_phone"`
	// The country code for `mobile_phone`
	MobilePhoneCountryCode string `json:"mobile_phone_country_code,omitempty"`
	// The email address on a profile
	Email string `json:"email,omitempty"`
	ShipToAddress *CustomerShipToAddress `json:"ship_to_address"`
	// Whether or not the profile uses express mail service
	ExpressMail string `json:"express_mail"`
	// The occupation of a person as listed in a profile
	Occupation string `json:"occupation"`
	// How the person on a profile earns income
	IncomeSource string `json:"income_source"`
	// List of account objects
	RelatedAccounts []CustomerRelatedAccounts `json:"related_accounts"`
}
