/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData57 struct {
	// Card holder prod ID
	CardHolderProdId int32 `json:"card_holder_prod_id"`
	// Funding prod ID
	FundingProdId int32 `json:"funding_prod_id"`
}
