/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData24 struct {
	// The old balance on the source account
	OldBalance float32 `json:"old_balance"`
	// The new balance on the source account
	NewBalance float32 `json:"new_balance"`
	// The trans ID associated with the adjustment
	AdjustmentTransId string `json:"adjustment_trans_id"`
	// The account associated with the transfer
	TransferAccountId string `json:"transfer_account_id"`
	// The fee applied to the C2C transfer
	SenderFeeAmount float32 `json:"sender_fee_amount"`
	// The transaction ID
	PaymentTransId string `json:"payment_trans_id"`
	TransferToAccount *ResponseData24TransferToAccount `json:"transfer_to_account"`
}
