/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreateHold struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// Currency amount as a whole or decimal amount. Pattern: Positive integer or decimal number Example: `100.00`, `100`, or `100.73`
	Amount float32 `json:"amount"`
	// Date and time when the hold expires. Pattern: YYYY-MM-DD hh:mm:ss Example: `\"2017-01-01 13:00:00\"`
	ExpirationDateTime time.Time `json:"expirationDateTime"`
	// The ID of the payment to hold: `payment_trans_id` as returned by the <a href=\"ref:post_createpayment\" target=\"_blank\">Create Payment</a> endpoint or `pmt_id` as returned by the <a href=\"ref:post_getpaymenthistory\" target=\"_blank\">Get Payment History</a> endpoint. Pattern: Positive integer Example: `4234888`
	PmtId int32 `json:"pmtId,omitempty"`
	// Transaction type for the hold. Use the values provided by Galileo for your program. Pattern: 2 alphanumeric characters Example: `\"MO\"`
	HoldType string `json:"holdType,omitempty"`
	// Description for the hold. Pattern: Max 80 alphanumeric characters, including punctuation Example: `\"One time payroll load.\"`
	Description string `json:"description,omitempty"`
	// External identifier for a hold. Pattern: Max 60 alphanumeric characters Example: `\"45348bacd483348\"`
	ExternalId string `json:"externalId,omitempty"`
}
