/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type ResponseData3SavingsInterest struct {
	// The start date for the period
	StartDate time.Time `json:"start_date"`
	// The end date for the period
	EndDate time.Time `json:"end_date"`
	// Interest accrued on the account. May return an integer if the interest accrued is 0.
	AccrualInterest *interface{} `json:"accrual_interest"`
	// The year-to-date interest paid on a savings account. May return an integer if the interest paid is 0.
	InterestYtd *interface{} `json:"interest_ytd"`
	// The amount earned with compound interest over the course of one year. May return an integer if the amount earned is 0.
	Apy *interface{} `json:"apy"`
}
