/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Echo struct {
	// An ID that represents an API transaction
	TransactionId string `json:"transaction_id"`
	// Store a related timestamp for reporting and troubleshooting purposes
	ProviderTimestamp time.Time `json:"provider_timestamp"`
	// Secondary transaction identifier (generated by a provider)
	ProviderTransactionId string `json:"provider_transaction_id"`
}
