/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData struct {
	// The start date for the transaction range
	StartDate time.Time `json:"start_date"`
	// The end date for the transaction range
	EndDate time.Time `json:"end_date"`
	// The total number of pages available in the paginated response
	NumberOfPages int32 `json:"number_of_pages"`
	// The current page being retunred in the paginated response
	Page int32 `json:"page"`
	// Number of records in the accounts list display
	TotalRecordCount int32 `json:"total_record_count"`
	// The number of transactions listed in the response
	TransactionCount int32 `json:"transaction_count"`
	// List of transactions
	Transactions []ResponseDataTransactions `json:"transactions"`
}
