/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData135 struct {
	// A vendor token that is used to switch direct deposit
	Token string `json:"token"`
	// The date and time a token expires
	Expires time.Time `json:"expires,omitempty"`
	// A vendor unique identifier that is used to switch direct deposit and identify the account for user
	VendorIdentifier string `json:"vendor_identifier"`
}
