/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData90Locations struct {
	// The type of agent that ran the transaction
	AgtType string `json:"agt_type"`
	// The name of the location
	Name string `json:"name"`
	// Street address of the location
	Addr string `json:"addr"`
	// City of the location
	City string `json:"city,omitempty"`
	// State of the location
	State string `json:"state"`
	// Postal code of the location
	Zip string `json:"zip"`
	// The main phone number on the account
	Phone string `json:"phone"`
	// Latitude coordinate of the location
	Latitude float32 `json:"latitude"`
	// Longitude coordinate of the location
	Longitude float32 `json:"longitude"`
	// The code for the agent that ran the transaction
	LoadAgentsId int32 `json:"load_agents_id"`
}
