/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateAchTransaction struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// ACH account identifier (`ach_account_id`), as returned by the <a href=\"ref:post_addachaccount\" target=\"_blank\">Add ACH Account</a> or <a href=\"ref:post_getachaccounts\" target=\"_blank\">Get ACH Accounts</a> endpoint. Pattern: Positive integer Example: `354656`
	AchAccountId int32 `json:"achAccountId"`
	// Currency amount as a whole or decimal amount. Pattern: Positive integer or decimal number Example: `100.00`, `100`, or `100.73`
	Amount float32 `json:"amount"`
	// Description for the ACH transfer. Pattern: Alphanumeric and punctuation, max 30 characters Example: `One time payroll load.`
	Description string `json:"description,omitempty"`
	// Specifies whether the recipient account is to be credited or debited. Default: `D`. * `C` &mdash; Credit * `D` &mdash; Debit  Pattern: `D` or `C` Example: `D`
	DebitCreditIndicator string `json:"debitCreditIndicator"`
	// Specifies whether this is a same-day transaction. Pattern: `Y` or `N` Example: `Y`
	SameDay string `json:"sameDay,omitempty"`
	// Specifies whether the transaction should be posted to the account immediately. Using this parameter requires provider parameter PSTNW to be set. Pattern: `Y` or `N` Example: `Y`
	PostImmediate string `json:"postImmediate,omitempty"`
	// Provider-supplied identifier, external to the Galileo system. This value is only required for the `CIE` and `WEB` <a href=\"page:sec-codes-requirements-for-ach\" target=\"_blank\">SEC codes</a>. Pattern: Max 22 characters Example: `\"123456789\"`
	IdentNumber string `json:"identNumber,omitempty"`
	// Obtained from Plaid if using Plaid integration. Checks the balance of the ACH account to verify that there are sufficient funds for an ACH debit. Pattern: String Example: `\"processor-production-35cd43b-adfc-d8aa-b331-c9ba0fdha881\"`
	ProcessorToken string `json:"processorToken,omitempty"`
	// The number of hold days to apply to this transaction, which overrides the hold days in product settings. This value applies only to outgoing ACH debits (`debitCreditIndicator: D`). This parameter is available only to clients who have obtained bank approval to use it. The ACOHD parameter must be set to use this parameter. Pattern: Positive integer Example: 2
	HoldDays int32 `json:"holdDays,omitempty"`
}
