/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData124 struct {
	// The page number retrieved in the context of recordset paging
	Page float64 `json:"page"`
	// The number of records in the display
	TotalRecordCount float64 `json:"total_record_count"`
	// Total number of pages in the accounts list display
	NumberOfPages float64 `json:"number_of_pages"`
	// List of information on pending merchant credits
	PendingMerchantCredits []ResponseData124PendingMerchantCredits `json:"pending_merchant_credits"`
}
