/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A structure for the response data. It can be empty but usually will contain information.
type VerifyInstantIssueCardResponseResponseData struct {
	// The status of the card
	Status string `json:"status"`
	// A Galileo generated account number
	PmtRefNo string `json:"pmt_ref_no"`
	// Galileo generated product ID of the account
	ProdId string `json:"prod_id"`
	// The maximum amount that can be loaded on a card
	MaxLoadAmount string `json:"max_load_amount"`
	// Integer identifier of the card as found in the raw dta file (RDF). Unique identifier for a PAN.
	CardId string `json:"card_id"`
	// A PAN or 16 digit card number
	CardNumber string `json:"card_number"`
	// Expiration date of the card
	ExpiryDate string `json:"expiry_date"`
	// The card verification value (cvv), is a card anti-fraud measure
	CardSecurityCode string `json:"card_security_code"`
	// The ID of a request for a batch of instant issue cards to be created
	BatchId string `json:"batch_id"`
	// Physical cards are shipped in bundles, which are divided by boxes. A case_id is a tracking number on each box and bundle.
	CaseId string `json:"case_id"`
	// A shipping tracking number on a box of shipped cards
	BoxId string `json:"box_id"`
	// A shipping tracking number on the bundle of shipped cards
	BundleId string `json:"bundle_id"`
	// A code for the location at which account was created, if applicable. Can be provided by client or Galileo
	GalileoLocationId string `json:"galileo_location_id"`
	// A code for the partner location
	PartnerLocationId string `json:"partner_location_id"`
}
