/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData41 struct {
	// The number of federal benefit enrollments found for the account
	Found int32 `json:"found"`
	// A list if enrollment objects
	Results []ResponseData41Results `json:"results"`
}
