/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData23 struct {
	// A code used to give the status of the simulated auth settlement
	SettleResponseCode string `json:"settle_response_code"`
	// A description of the settlement response
	SettleResponseDescription string `json:"settle_response_description"`
	// An ID associated with the simulated settlement
	SettleDtl string `json:"settle_dtl"`
}
