/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData81 struct {
	// Status of the card order: `P` - Processed; `E` - Error
	Status string `json:"status"`
	// Identifier for the product associated with the card order
	ProdId string `json:"prod_id"`
	// Identifier for the card order
	OrderId string `json:"order_id"`
	// Number of cards in the order
	NumberOfCards int32 `json:"number_of_cards"`
	// First line to be embossed on cards
	EmbossWith string `json:"emboss_with"`
	// Shipping name the for card order
	ShipToName string `json:"ship_to_name"`
	// Address for shipping card order
	ShipToAddress string `json:"ship_to_address"`
	// City for shipping address
	ShipToCity string `json:"ship_to_city"`
	// State or province for the shipping address
	ShipToStateOrProvince string `json:"ship_to_state_or_province"`
	// Postal code for the shipping address
	ShipToPostalCode string `json:"ship_to_postal_code"`
	// Location for cards
	Location string `json:"location"`
	// Location name for cards
	LocationName string `json:"location_name"`
	// Location type for cards
	LocationType int32 `json:"location_type"`
	// This field returns zeros only
	CardIdRangeStart int32 `json:"card_id_range_start"`
	// This field returns zeros only
	CardIdRangeEnd int32 `json:"card_id_range_end"`
	// List of transfer accounts
	Cards []ResponseData81Cards `json:"cards"`
}
