/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MoveCardInventoryBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// Galileo-generated identifier for a product. Pattern: Integer Example: `501`
	ProdId int32 `json:"prodId,omitempty"`
	// Identifier for the current location (`location`) as returned by the <a href=\"ref:post_createlocation\" target=\"_blank\">Create Location</a> endpoint. This value is also returned by the <a href=\"ref:post_getlocations\" target=\"_blank\">Get Locations</a> endpoint depending on the value of `locationType` when the location was created: * `0` &mdash; Returned in the `location_id` field * `1` &mdash; Returned in the `provider_specified_id` field  Pattern: Integer if `locationType: 0`; max 15 characters if `locationType: 1 Example: `\"a455-3483\"`
	Location string `json:"location"`
	// Type of ID in `location`: * `0` &mdash; Galileo location ID * `1` &mdash; Partner location ID  Pattern: `0` or `1` Example: `1`
	LocationType int32 `json:"locationType"`
	// Identifier for the new location (`location`) as returned by the <a href=\"ref:post_createlocation\" target=\"_blank\">Create Location</a> endpoint. This value is also returned by the <a href=\"ref:post_getlocations\" target=\"_blank\">Get Locations</a> endpoint depending on the value of `locationType` when the location was created: * `0` &mdash; Returned in the `location_id` field * `1` &mdash; Returned in the `provider_specified_id` field  Pattern: Integer if `moveToLocationType: 0`; max 15 characters if `moveToLocationType: 1` Example: `\"3\"`
	MoveToLocation string `json:"moveToLocation"`
	// Type of location in `moveToLocation`: * `0` &mdash; Galileo location ID * `1` &mdash; Provider location ID  Pattern: `0` or `1` Example: `1`
	MoveToLocationType int32 `json:"moveToLocationType"`
	// The type of inventory move: * `P` &mdash; Card ID * `B` &mdash; Bundle ID * `O` &mdash; Box ID * `C` &mdash; Case ID  Pattern: One character Example: `\"P\"`
	Type_ string `json:"type"`
	// Start of the ID range or a single ID. Pattern: Positive integer Example: `\"100\"`
	RangeStart string `json:"rangeStart"`
	// End of ID range. Omit this parameter if there is no range. Pattern: Positive integer Example: `\"200\"`
	RangeEnd string `json:"rangeEnd,omitempty"`
}
