/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddSecureMessage struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// Secure message subject Pattern: Alphanumeric string including punctuation; maximum 255 characters Example: `\"account login help pls\"`
	MsgSubject string `json:"msgSubject,omitempty"`
	// Secure message body text Pattern: Alphanumeric string including punctuation; maximum 4000 characters Example: `\"Please help me recover my password.\"`
	MsgText string `json:"msgText,omitempty"`
	// The msgId of the original cardholder message that you wish to respond to. Pattern: Positive integer value Example: `483383`
	ParentMsgId string `json:"parentMsgId,omitempty"`
	// Sets customer language preference. Default is \"en_US\". Pattern: Accepted values = `en_US`, `es_US`, `fr_CA`, `en_CA`, `es_MX`, and `en_MX` Example: `\"en_US\"`
	Locale string `json:"locale,omitempty"`
}
