/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData115 struct {
	// The balance on the account after the transaction
	NewBalance float64 `json:"new_balance,omitempty"`
	// The new expiration date associated with the hold
	NewExpirationDate time.Time `json:"new_expiration_date,omitempty"`
}
