/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A structure for the response data. It can be empty but usually will contain information.
type GetTopUpResponseResponseData struct {
	// Top up Amount
	Amount float32 `json:"amount"`
	// The top up date
	TopUpEndDate time.Time `json:"top_up_end_date"`
}
