/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData59 struct {
	// The number of active cards
	ActiveCards int32 `json:"active_cards"`
	// The number of new cards
	NewCards int32 `json:"new_cards"`
	// Funds loaded
	FundsLoaded float32 `json:"funds_loaded"`
	// Funds spent
	FundsSpent float32 `json:"funds_spent"`
	// Number accounts created
	NumberAccountsCreated string `json:"number_accounts_created"`
	// Accounts limit
	NumberAccountsLimit string `json:"number_accounts_limit"`
}
