/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A structure for the response data. It can be empty but usually will contain information.
type GetBillersResponseResponseData struct {
	// List of billers
	Billers []ResponseData15Billers `json:"billers"`
	// The total number of billers found
	Found int32 `json:"found"`
	// The page number to be retrieved in the context of recordset paging
	Page int32 `json:"page"`
	// Number of records in the accounts list display
	TotalRecordCount int32 `json:"total_record_count"`
	// Total number of pages in the accounts list display
	NumberOfPages int32 `json:"number_of_pages"`
}
