/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A structure for the response data. It can be empty but usually will contain information.
type SetUserDefinedAccountFieldResponseResponseData struct {
	// A field identifier or key name
	FieldId string `json:"field_id"`
	// A value placed into the created field
	FieldValue string `json:"field_value"`
	// A time and date stamp that shows the last time the custom field was modified
	LastModified time.Time `json:"last_modified"`
}
