/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetDirectDepositSwitchToken struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the local account. Do not use the <<glossary:CAD>>. Pattern: 12-digit or 16-digit numeric string Example: `\"344101254935\"`
	AccountNo string `json:"accountNo"`
	// PAN or PRN of the account that will receive the direct deposit. Do not use the CAD. Can be the same account number as `accountNo`.  Pattern: 12-digit or 16-digit numeric stringExample: `\"722844300741\"`
	DdAccountNo string `json:"ddAccountNo"`
	// Routing number for the account in `ddSwitchAccountNo`. Pattern: 9-digit routing number, including check digit Example: `\"124001545\"`
	DdRoutingNo string `json:"ddRoutingNo"`
	// Type of account in `ddSwitchAccountNo`. Pattern: `checking` or `savings` Example: `\"checking\"`
	DdAccountType string `json:"ddAccountType"`
	// Description for the direct deposit account. Pattern: Max 50 characters: letters, numbers, spaces, hyphens, underscores. Example: `\"Galileo Plus Checking account\"`
	DdAccountDescription string `json:"ddAccountDescription,omitempty"`
}
