/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A structure for the response data. It can be empty but usually will contain information.
type ActivateCardResponseResponseData struct {
	// UUID for an emboss record that has been sent to the embosser. When this field is present outside the `embossed_cards` object, it contains the most recent emboss UUID.
	EmbossUuid string `json:"emboss_uuid,omitempty"`
	// If the PRN is passed as accountNo, displays the selected card if the cardholder has more than one active card related to their account
	CardNumberLastFour string `json:"card_number_last_four"`
}
