/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CreditLimit struct {
	// The credit limit amount
	Amount string `json:"amount,omitempty"`
	// Timestamp when the credit limit was last changed
	LastChanged time.Time `json:"last_changed,omitempty"`
}
