/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData89Locations struct {
	// The numerical value assigned to the location
	LocationId int32 `json:"location_id"`
	// The name of the location
	Name string `json:"name"`
	// Address 1 of the location
	Address1 string `json:"address1"`
	// Address 2 of the location
	Address2 string `json:"address2"`
	// City of the location
	City string `json:"city"`
	// State of the location
	State string `json:"state"`
	// Postal code of the location
	PostalCode string `json:"postalCode"`
	// The numerical ID of the parent location
	ParentLocationId string `json:"parent_location_id"`
	// The partner or program identity for a location
	ProviderSpecifiedId string `json:"provider_specified_id"`
	// Indicates a central corporate credit aggregate billing location. Allows one centralized billing location for all invoice records attached to the location.
	CentralBillFlag int32 `json:"centralBillFlag,omitempty"`
	// The credit limit for this location
	CreditLimit float32 `json:"creditLimit,omitempty"`
	// The store or location type. Values are `Corporate`, `Chain`, `Reseller`, `Region`, or `Store`.
	StoreType string `json:"store_type"`
	// Current status of the location. Values are `Closed`, `Active`, `Suspended`, or `New`.
	Status string `json:"status"`
	// List of fees attached to the location
	Fees []LocationFees `json:"fees,omitempty"`
}
