/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SearchBillerDirectory struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// Valid biller account number. As applicable, this value is validated against a biller-supplied mask. Pattern: A Max 60 alphanumeric characters including space and hyphen Example: `\"3333223323455555\"`
	BillerAccountNo string `json:"billerAccountNo,omitempty"`
	// Pass a complete or partial name of a biller to begin the search. When a single term returns multiple entries, the account holder must select from among them. Pass `billerState` and/or `billerAccountNo` to filter the results. Pattern: Max 50 alphanumeric characters, no punctuation Example: `\"Netflix\"`
	BillerName string `json:"billerName"`
	// Biller state or province. Pattern: 2-character state or provincial abbreviation Example: `\"UT\"`
	BillerState string `json:"billerState,omitempty"`
}
