/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A data structure that contains information about one or more features.
type ResponseData42Features struct {
	// Identifier for the feature type
	Type_ int32 `json:"type"`
	// Description of the feature type specified in the `type` field
	Name string `json:"name"`
	// A value associated with the feature type specified in the `type` field
	Value string `json:"value"`
	// The feature start date
	StartDate string `json:"start_date"`
	// The feature end date
	EndDate string `json:"end_date"`
}
