/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData102AchAccounts struct {
	// A unique ID for an ACH account
	AchAccountId string `json:"ach_account_id"`
	// The status of the ACH account. See <a href=\"ref:api-reference-ach-account-statuses\" target=\"_blank\">ACH Account Statuses</a>.
	Status string `json:"status"`
	// A number used to associate a transaction with an institution
	RoutingNo string `json:"routing_no"`
	// A number use to associate a transaction with an account
	AccountNo string `json:"account_no"`
	// The type of record being displayed
	Type_ string `json:"type"`
	// The name of the ACH account being displayed
	Name string `json:"name"`
	// Name of the company that owns the ACH account. Returned when `entity_type: C`.
	CompanyName string `json:"company_name"`
	// Type of account holder of the ACH account: individual (`I`) or company (`C`).
	EntityType string `json:"entity_type"`
	// First name of the ACH account holder. Returned when `entity_type: I`.
	FirstName string `json:"first_name"`
	// Last name of the ACH account holder. Returned when `entity_type: I`
	LastName string `json:"last_name"`
	// First name of the individual account holder that is used in the outgoing Nacha file. Returned when `entity_type: I`
	FileFirstName string `json:"file_first_name"`
	// Last name of the individual account holder that is used in the outgoing Nacha file. Returned when `entity_type: I`
	FileLastName string `json:"file_last_name"`
	FileCompanyName string `json:"file_company_name"`
}
