/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetBulkCardOrderBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// The order ID (`order_id`) as returned by the <a href=\"ref:post_createbulkcardorder\" target=\"_blank\">Create Bulk Card Order</a> endpoint. Pattern: Positive integer Example: `5068`
	OrderId int32 `json:"orderId"`
	// Type of ID in `location`: * `0` &mdash; Galileo location ID * `1` &mdash; Partner location ID * `2` &mdash; Don't validate  Pattern: `0`, `1`, or `2` Example: `1`
	LocationType int32 `json:"locationType,omitempty"`
	// Specifies whether to return a list of all cards in the order, in the `cards` object: * `0` &mdash; Do not return cards * `1` &mdash; Return all cards  Pattern: `0` or `1` Example: `0`
	ReturnAllCards int32 `json:"returnAllCards,omitempty"`
}
