/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateBulkCardOrderBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// Galileo-generated identifier for a product. Pattern: Integer Example: `501`
	ProdId int32 `json:"prodId"`
	// Number of cards to be created. Pattern: Positive integer Example: `1000`
	NumberOfCards int32 `json:"numberOfCards"`
	// Optional string to be printed on the first emboss line of the cards. Pattern: Max 20 alphanumeric characters Example: `\"Bob's cards\"`
	EmbossWith string `json:"embossWith,omitempty"`
	// In-care-of name for the address where the bulk card order is to be shipped. Pattern: Max 40 alphanumeric characters Example: `\"c\"`
	ShipToName string `json:"shipToName"`
	// Street address where the bulk order is to be shipped. Pattern: Max 40 alphanumeric characters Example: `\"33 Maple Street\"`
	ShipToAddress string `json:"shipToAddress"`
	// City where the bulk order is to be shipped. Pattern: Max 20 alphanumeric characters Example: `\"Salt Lake City\"`
	ShipToCity string `json:"shipToCity"`
	// State or province where the bulk order is to be shipped. Pattern: 2-character state or province code Example: `\"UT\"`
	ShipToStateOrProvince string `json:"shipToStateOrProvince"`
	// Postal code where the bulk order is to be shipped Pattern: `12345`, `12345-6789`, or `K1A-1A1` Example: `\"84121\"`
	ShipToPostalCode string `json:"shipToPostalCode"`
	// Location identifier as returned by <a href=\"ref:post_createlocation\" target=\"_blank\">Create Location</a> (`location`) or <a href=\"ref:post_getlocations\" target=\"_blank\">Get Locations</a> (`location_id` or `provider_specified_id`). Pattern: Integer if `location` or `location_id`; max 15 characters if `provider_specified_id` Example: `\"a455-3483\"`
	Location string `json:"location"`
	// Type of ID in `location`: * `0` &mdash; Galileo location ID * `1` &mdash; Partner location ID  Pattern: `0` or `1` Example: `1`
	LocationType int32 `json:"locationType,omitempty"`
}
