/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModifyLocationFeeBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// Identifier for the location that was created with Create Location. This value is returned by Get Locations in the `location_id` field when `locationType: 0` or `locationType: 2`, or in the `provider_specified_id` field when `locationType: 1`. Pattern: Must be a number if type is 0; Must be less than or equal to 15 characters if type is 1. Example: `\"a455-3483\"`
	Location string `json:"location"`
	// Location type, as specified by Create Location. 0=Galileo location ID, 1=Partner location ID, 2=Don't validate. Pattern: `0`, `1` or `2` Example: `\"0\"`
	LocationType int32 `json:"locationType"`
	// Type of fee as specified by Create Location Fee. This value must be the original value provided at the time of the fee creation: `FBD` (FBE direct deposit fee) or `DEL` (ACH direct deposit fee) Pattern: `FBD` or `DEL` Example: `\"FBD\"`
	FeeType string `json:"feeType"`
	// Specify either a flat amount or a percentage. For a flat amount the valid range is between `.01` and `999`. For a percentage the valid range is `.01` (1%) to `1` (100%). When this parameter is populated then `amountType` is required. Pattern: 1, 1.10, 0.5 Example: 1.23
	Amount float32 `json:"amount,omitempty"`
	// Specify whether the value in `amount` is a flat rate (`flat`) or a percentage (`percent`). When this parameter is populated then `amount` is required. Pattern: `flat` or `percent` Example: 'flat'
	AmountType string `json:"amountType,omitempty"`
	// The minimum amount for the fee, if the amount type is a percentage. Pattern: 10, 20.5, 2.33 Example: 1.10
	MinFee float32 `json:"minFee,omitempty"`
	// The maximum amount for the fee, if the amount type is a percentage. Pattern: 10, 20.5, 2.33 Example: 1.10
	MaxFee float32 `json:"maxFee,omitempty"`
	// Specify whether to activate the fee (`Y`) or deactivate the fee (`N`). Pattern: `Y` or `N` Example: `\"Y\"`
	Active string `json:"active,omitempty"`
}
