/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApprovedMerchants struct {
	// An integer that identifies a merchant
	MerchId string `json:"merch_id"`
	// An ID used to identify the merchant
	OtherId string `json:"other_id"`
	// A flag for if Galileo Processing has approved the transaction or not
	Isapproved string `json:"isapproved"`
	// A parsed merchant description
	MerchDesc string `json:"merch_desc"`
	// Number assigned to an authorization
	AuthId string `json:"auth_id"`
	// A code that identifies the card issuer. `V`=Visa `M`=MC `D`=MC Debit
	Network string `json:"network"`
	// Number of transactions with the listed merchant
	TotalTrans string `json:"total_trans"`
}
