/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Account4 struct {
	// A Galileo generated account number
	PmtRefNo string `json:"pmt_ref_no"`
	// A person's first name as listed on the account
	FirstName string `json:"first_name"`
	// A person's middle name as listed on the account
	MiddleName string `json:"middle_name"`
	// A person's last name as listed on the account
	LastName string `json:"last_name"`
	// The email address on a profile
	Email string `json:"email"`
	// The status of the account
	Status string `json:"status"`
	// Yes or no to flag an active account
	Active string `json:"active"`
	// Galileo generated integer account number, also known as balance ID
	GalileoAccountNumber string `json:"galileo_account_number"`
	// Galileo generated integer
	ProductId string `json:"product_id"`
	// Integer value used for tracking the location (store, entity, etc...) where the customer was acquired. The group_id is set using the location and locationType parameters.
	GroupId string `json:"group_id"`
	// The date an application was made to create an account
	ApplicationDate time.Time `json:"application_date"`
}
