/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A structure for the response data. It can be empty but usually will contain information.
type GetSavingsInterestResponseResponseData struct {
	// Interest accrued on account
	AccrualInterest float32 `json:"accrual_interest"`
	// The interest paid on a savings account from the start date to the end date
	InterestYtd string `json:"interest_ytd"`
	// The actual interest rate used to calculate compound interest over the course of one year
	Apy string `json:"apy"`
	// The start date of a response
	StartDate time.Time `json:"start_date"`
	// The end date of a response
	EndDate time.Time `json:"end_date"`
	// The carry over interest pending on a savings account on the end date
	CarryOver float32 `json:"carry_over"`
}
