/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseData95 struct {
	// The check number
	CheckNumber string `json:"check_number"`
	// The amount the check is for
	Amount string `json:"amount"`
	// The bank routing number for the check
	BankRoutingNumber string `json:"bank_routing_number"`
	// The bank account number for the check
	BankAccountNumber string `json:"bank_account_number"`
	// The status of the convenience check
	Status string `json:"status"`
	// The date the check was authorized
	AuthorizedDate time.Time `json:"authorized_date"`
	// A code for the authorization
	AuthorizationCode string `json:"authorization_code"`
	// Who the check is written to
	Payee string `json:"payee"`
}
