/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A structure for the response data. It can be empty but usually will contain information.
type GenerateProviderCredentialsResponseResponseData struct {
	// apii user ID
	ApiiUserId int32 `json:"apii_user_id"`
	// Login id
	LoginId int32 `json:"login_id"`
	// transaction key
	TransKey float32 `json:"trans_key"`
	// The date of creation
	DateCreated float32 `json:"date_created"`
	// The expiration date
	DateExpires string `json:"date_expires"`
	// user defined name
	UserDefinedName string `json:"user_defined_name"`
}
