/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetMerchantControlsBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// The <<glossary:PRN>> for the account. Do not use the <<glossary:CAD>> or <<glossary:PAN>>. Pass this value to retrieve all of the account-level MID controls for this account. If this parameter is not populated then `prodId` must be populated. Pattern: PRN (12-digit numeric string) Example: `\"074103447228\"`
	AccountNo string `json:"accountNo,omitempty"`
	// The Galileo-generated identifier for the product. Pass this value to retrieve all of the product-level MID controls for this product. If this parameter is not populated then `accountNo` must be populated. Pattern: Integer Example: `15293`
	ProdId int32 `json:"prodId,omitempty"`
}
