/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData55 struct {
	// The current page in the accounts list display
	Page int32 `json:"page"`
	// Number of records in the accounts list display
	TotalRecordCount string `json:"total_record_count"`
	// Total number of pages in the accounts list display
	NumberOfPages int32 `json:"number_of_pages"`
	// List of account objects
	Accounts []ResponseData55Accounts `json:"accounts"`
}
