/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdatePendingMerchantCreditBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// The `settle_id` as returned by <a href=\"ref:post_getpendingmerchantcredits\" target=\"_blank\">Get Pending Merchant Credits</a>. Pattern: `/^[a-z A-Z]{1}-[0-9]{1,20}$/` Example: `\"v-43843747\"`
	SettleId string `json:"settleId"`
	// Type of update to perform on the merchant credit: * `1` &mdash; Post * `2` &mdash; Post and hold  Pattern: `1` or `2` Example: `\"2\"`
	Type_ string `json:"type"`
	// Galileo-generated identifier for the program. Pattern: Positive integer Example: `1032`
	ProgramId int32 `json:"programId"`
}
