/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData33 struct {
	// Identifier for the enrollment application
	AppId string `json:"appId"`
	Cip []ResponseData33Cip `json:"cip,omitempty"`
	// Maximum credit limit
	MaxCreditLimit string `json:"max_credit_limit,omitempty"`
}
