/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CompleteEnrollment struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// Unique location identifier (`location`) as returned by the <a href=\"ref:post_createlocation\" target=\"_blank\">Create Location</a> endpoint.  This value is also returned by the <a href=\"ref:post_getlocations\" target=\"_blank\">Get Locations</a> endpoint depending on the value of `locationType` when the location was created: * `0` or `2` &mdash; Returned in the `location_id` field * `1` &mdash; Returned in the `provider_specified_id` field  Pattern: Integer if `locationType: 0` or `locationType: 2`; max 15 characters if `locationType: 1` Example: `\"a455-3483\"`
	Location string `json:"location,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PRN or PAN Example: `\"074103447228\"`
	AccountNo string `json:"accountNo,omitempty"`
	// Galileo-generated identifier for a product. If this ID is for a business product then `businessName` is **required**. Pattern: Integer Example: `501`
	ProdId int32 `json:"prodId"`
	// Type of ID in `location`: * `0` &mdash; Galileo location ID * `1` &mdash; Partner location ID * `2` &mdash; Don't validate  Pattern: `0` or `1` Example: `1`
	LocationType int32 `json:"locationType,omitempty"`
	// Specifies whether the secondary account will share the balance of the primary account. This parameter is **required** when `primaryAccount` is populated. Do not set this parameter to `1` when `primaryAccount` is not populated. * `0` &mdash; Do not share the balance * `1` &mdash; Share the balance  Pattern: One digit Example: `1`
	SharedBalance int32 `json:"sharedBalance,omitempty"`
	// 0=on line transaction, 1=offline transaction Pattern: `0` or `1` Example: `1`
	Offline int32 `json:"offline,omitempty"`
	// <<glossary:PAN>> or <<glossary:PRN>> of the primary account to associate this account with. Populate this parameter only when creating a secondary account. Pattern: PAN or PRN Example: `\"123456789012\"`
	PrimaryAccount string `json:"primaryAccount,omitempty"`
	// Identifier supplied by the provider, which is not related to the Galileo system. This ID is stored in the Galileo system in association with this account and can be provided in the <<glossary:RDF>>s. Pattern: Max 30 alphanumeric characters Example: `\"553b45sbs\"`
	ExternalAccountId string `json:"externalAccountId,omitempty"`
	// Second line to emboss on the card. Pattern: Max 28 alphanumeric characters, including hyphen (`-`) Example: `\"second emboss line\"`
	EmbossLine2 string `json:"embossLine2,omitempty"`
	// PRN of the <<glossary:RTF>> funding account. **Required** if `prodId` is an RTF spending product. Pattern: 12-digit numeric string Example: `\"143101204201\"`
	FundingAccountNo string `json:"fundingAccountNo,omitempty"`
}
