/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Card1FreezeInfo struct {
	// Flag showing whether a card is frozen or not
	Status string `json:"status"`
	// Start date for card being frozen
	StartDate time.Time `json:"start_date"`
	// End date for card being frozen
	EndDate time.Time `json:"end_date"`
}
