/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateLocationFeeArgs struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// Unique location identifier (`location`) as returned by the <a href=\"ref:post_createlocation\" target=\"_blank\">Create Location</a> endpoint.  This value is also returned by the <a href=\"ref:post_getlocations\" target=\"_blank\">Get Locations</a> endpoint depending on the value of `locationType` when the location was created: * `0` or `2` &mdash; Returned in the `location_id` field * `1` &mdash; Returned in the `provider_specified_id` field  Pattern: Integer if `locationType: 0` or `locationType: 2`; max 15 characters if `locationType: 1` Example: `\"a455-3483\"`
	Location string `json:"location"`
	// Type of ID in `location`: * `0` &mdash; Galileo location ID * `1` &mdash; Partner location ID * `2` &mdash; Don't validate  Pattern: `0`, `1`, or `2` Example: `0`
	LocationType int32 `json:"locationType"`
	// Type of fee to assess at this location. To set up both fee types at the same location, call this endpoint twice: * `FBD` &mdash; Federal benefit enrollment direct-deposit fee * `DEL` &mdash; ACH direct-deposit fee  Pattern: 3-character code Example: `\"FBD\"`
	FeeType string `json:"feeType"`
	// Specify either a flat amount or a percentage. For a flat amount the valid range is between `.01` and `999`. For a percentage the valid range is `.01` (1%) to `1` (100%). When this parameter is populated then `amountType` is **required**. Pattern: Positive integer or decimal number Example: `1.23`
	Amount float32 `json:"amount"`
	// Specify which type of value is in `amount`: * `flat` &mdash; Flat rate * `percent` &mdash; Percentage  Pattern: String Example: `\"flat\"`
	AmountType string `json:"amountType"`
	// The minimum amount for the fee, when `amountType: percent`. Pattern: Positive integer or decimal number Example: `1.10`
	MinFee float32 `json:"minFee,omitempty"`
	// The maximum amount for the fee, when `amountType: percent`. Pattern: Positive integer or decimal number Example: `1.10`
	MaxFee float32 `json:"maxFee,omitempty"`
}
