/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData25 struct {
	// The number of deposits in the response
	DepositCount int32 `json:"deposit_count"`
	// The page number to be retrieved in the context of recordset paging
	Page int32 `json:"page"`
	// Total number of deposit records returned
	TotalRecordCount int32 `json:"total_record_count"`
	// Total number of pages
	NumberOfPages int32 `json:"number_of_pages"`
	// The start date for deposit records
	StartDate string `json:"start_date"`
	// The end date for deposit records
	EndDate string `json:"end_date"`
	Deposits []ResponseData25Deposits `json:"deposits"`
}
