/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateFundingTransaction struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// Currency amount as a whole or decimal amount. Pattern: Positive integer or decimal number Example: `100.00`, `100`, or `100.73`
	Amount float32 `json:"amount"`
	// Description for the ACH transfer. Pattern: Alphanumeric and punctuation, max 30 characters Example: `One time payroll load.`
	Description string `json:"description,omitempty"`
	// External account card number
	ExtCardNo string `json:"extCardNo"`
	// Card security code (CVV). This is not stored in Galileo systems.
	ExtCardSecurityCode string `json:"extCardSecurityCode"`
	// The funding card expiry date provided by the cardholder. Pattern: YYYY-MM Example: `\"2019-01\"`
	ExtCardExpiryDate string `json:"extCardExpiryDate"`
}
