/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReverseFeeBody struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	// The <<glossary:PRN>> or <<glossary:PAN>> of the account. Pattern: PAN or PRN  Example: `\"074103447228\"`
	AccountNo string `json:"accountNo"`
	// The fee ID (`fee_id`) of the fee to reverse, as returned by the <a href=\"ref:post_getfeehistory\" target=\"_blank\">Get Fee History</a> endpoint. Pass this value only if the fee was *not* created by the <a href=\"ref:post_assessfee\" target=\"_blank\">Assess Fee</a> endpoint.
	FeeId int32 `json:"feeId,omitempty"`
	// Pass `1` to test the validity of the parameter data without committing the information to the Galileo system. Pattern: `0` or `1` Example: `\"0\"`
	VerifyOnly string `json:"verifyOnly,omitempty"`
}
