/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData84 struct {
	// The number of records found
	TotalRecordCount int32 `json:"total_record_count"`
	// List of credit limit changes
	Changes []ResponseData84Changes `json:"changes"`
}
