/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData107Transactions struct {
	// Name of account associated with the transaction
	Name string `json:"name"`
	// Description for the transaction
	Description string `json:"description"`
	// A unique ID for an ACH transaction
	AchTransactionId string `json:"ach_transaction_id"`
	// The <a href=\"ref:api-reference-events-ach-return-codes\" target=\"_blank\">ACH return code</a>.
	RejectCode string `json:"reject_code"`
	// The datetime for the transaction. In the format: `yyyy-mm-dd hh:mm:ss`.
	Date string `json:"date"`
	// Status of transaction. See <a href=\"ref:api-reference-ach-transaction-statuses\" target=\"_blank\">ACH Transaction Statuses</a>.
	Status string `json:"status"`
	// ACH routing number
	AchRoutingNo string `json:"ach_routing_no"`
	// The ACH account number. May be masked depending on configuration.
	AchAccountNo string `json:"ach_account_no"`
	// Indicator of whether the transaction was a credit or debit. `D` or `C`.
	DebitCreditIndicator string `json:"debit_credit_indicator"`
	// Transaction amount
	Amount string `json:"amount"`
	// A Galileo generated account number
	PmtRefNo string `json:"pmt_ref_no"`
	// ID for the ACH account
	AchAccountId string `json:"ach_account_id"`
}
