/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData122 struct {
	// List of active holds
	ActiveHolds []ResponseData122ActiveHolds `json:"active_holds"`
	// List of expired holds
	ExpiredHolds []ResponseData122ActiveHolds `json:"expired_holds"`
}
