/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Biller1 struct {
	// Remote Payment and Presentment Service provider ID
	RppsBillerId string `json:"rpps_biller_id"`
	// Name of the biller
	BillerName string `json:"biller_name"`
	// Street and residence number on the account
	BillerAddress1 string `json:"biller_address1"`
	// Additional address information on the account
	BillerAddress2 string `json:"biller_address2"`
	// City for address information
	BillerCity string `json:"biller_city"`
	// State for address information
	BillerState string `json:"biller_state"`
	// Zip code for address information
	BillerZip string `json:"biller_zip"`
	// The account number patterns that are used by the biller. See the Account Patterns Legend below
	BillerAccountNoPatterns []string `json:"biller_account_no_patterns"`
}
