/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A structure for the response data. It can be empty but usually will contain information.
type GetAllTransHistoryResponseResponseData struct {
	// The number of transactions listed in the response
	TransactionCount int32 `json:"transaction_count"`
	// The page number to be retrieved in the context of recordset paging
	Page int32 `json:"page"`
	// Number of records in the accounts list display
	TotalRecordCount int32 `json:"total_record_count"`
	// Total number of pages in the accounts list display
	NumberOfPages int32 `json:"number_of_pages"`
	// Start date of the response
	StartDate time.Time `json:"start_date"`
	// End date of the response
	EndDate time.Time `json:"end_date"`
	Sums *ResponseData26Sums `json:"sums"`
	// List of transactions
	Transactions []ResponseData26Transactions `json:"transactions"`
	// The account balance as of the `startDate`.
	BeginningBalance float32 `json:"beginning_balance"`
}
