/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetAccountLevelMerchantControl struct {
	// Web service username, as provided by Galileo. Pattern: Max 50 characters Example: `\"AbC123-9999\"`
	ApiLogin string `json:"apiLogin,omitempty"`
	// Web service password, as provided by Galileo. Pattern: Max 15 characters Example: `\"4sb62fh6w4h7w34g\"`
	ApiTransKey string `json:"apiTransKey,omitempty"`
	// Galileo-issued provider identifier. Pattern: Max 10 digits Example: `9999`
	ProviderId int32 `json:"providerId,omitempty"`
	// A unique provider-generated ID to identify this API call. A UUID is preferred. This value is used for <a href=\"ref:idempotency\" target=\"_blank\">idempotency</a>. Pattern: 60 characters or less Example: `\"9845dk-39fdk3fj3-4483483478\"`
	TransactionId string `json:"transactionId"`
	LogQueries int32 `json:"logQueries,omitempty"`
	// The <<glossary:PRN>> for the account. Do not use the <<glossary:CAD>> or <<glossary:PAN>>. Pattern: PRN (12-digit numeric string) Example: `\"344101254935\"`
	AccountNo string `json:"accountNo"`
	// The merchant ID. Not case-sensitive. Pattern: Max 15 alphanumeric characters Example: `\"000534LECR08003\"`
	MerchantId string `json:"merchantId"`
	// Whether the merchant ID is ALLOW (`a`) or DENY (`d`). This parameter is required for new controls but optional for updates. Pattern: `a` or `d` Example: `\"d\"`
	AllowDeny string `json:"allowDeny,omitempty"`
	// Start date-time for the control. Can be set up to six months in the future. Cannot be in the past. Must be earlier than `endDate`. Default: Current <a href=\"ref:galileo-system-time\" target=\"_blank\">Galileo system time</a>  Pattern: YYYY-MM-DD hh:mm:ss or YYYY-MM-DD Example: `\"2022-03-03 00:00:00\"`
	StartDate string `json:"startDate,omitempty"`
	// End date-time for the control. Must be later than `startDate`. Cannot be in the past. Default: `3000-01-01 00:00:00`.  Pattern: YYYY-MM-DD hh:mm:ss or YYYY-MM-DD Example: `\"2022-03-10 23:59:59\"`
	EndDate string `json:"endDate,omitempty"`
}
