/*
 * Program API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseData96 struct {
	// The number of transfer accounts found
	Found int32 `json:"found"`
	// List of transfer accounts
	TransferAccounts []ResponseData96TransferAccounts `json:"transfer_accounts"`
}
